# Makefile for Salary Manager C++ MySQL Project
# Author: Auto-generated
# Version: 1.0

# Compiler settings
CXX = g++
CXXFLAGS = -std=c++14 -Wall -Wextra -g -O2
INCLUDES = -I./include -I/usr/include/mysql -I/usr/local/include/mysql++ -I/usr/include/cppconn
LDFLAGS = -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib
LIBS = -lmysqlcppconn -lmysqlclient

# Directories
SRC_DIR = src
INC_DIR = include
BIN_DIR = bin
BUILD_DIR = build

# Source files
SOURCES = $(wildcard $(SRC_DIR)/*.cpp)
OBJECTS = $(SOURCES:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)
TARGET = $(BIN_DIR)/salary_manager

# Default target
all: directories $(TARGET)

# Create necessary directories
directories:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(BUILD_DIR)

# Build the main executable
$(TARGET): $(OBJECTS)
	@echo "Linking $(TARGET)..."
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS) $(LIBS)
	@echo "Build successful! Executable: $(TARGET)"

# Compile source files to object files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# Clean build files
clean:
	@echo "Cleaning build files..."
	rm -rf $(BUILD_DIR)/*.o $(TARGET)
	@echo "Clean complete!"

# Clean everything including directories
distclean: clean
	rm -rf $(BUILD_DIR) $(BIN_DIR)

# Install dependencies (Ubuntu/Debian)
install-deps:
	@echo "Installing MySQL C++ Connector dependencies..."
	sudo apt-get update
	sudo apt-get install -y libmysqlcppconn-dev libmysqlclient-dev mysql-server
	@echo "Dependencies installed!"

# Install dependencies (CentOS/RHEL/Fedora)
install-deps-rpm:
	@echo "Installing MySQL C++ Connector dependencies..."
	sudo yum install -y mysql-connector-c++-devel mysql-devel mysql-server
	# Or for newer versions: sudo dnf install mysql-connector-c++-devel mysql-devel mysql-server
	@echo "Dependencies installed!"

# Run the application
run: $(TARGET)
	@echo "Running Salary Manager..."
	./$(TARGET)

# Debug build
debug: CXXFLAGS += -DDEBUG -g3
debug: all

# Release build
release: CXXFLAGS += -DNDEBUG -O3
release: all

# Test database connection
test-db:
	@echo "Testing MySQL connection..."
	mysql -u root -p -e "SELECT 'MySQL connection successful!' as message;"

# Setup database
setup-db:
	@echo "Setting up database..."
	mysql -u root -p < sql/database_schema.sql
	@echo "Database setup complete!"

# Help target
help:
	@echo "Available targets:"
	@echo "  all          - Build the application (default)"
	@echo "  clean        - Remove object files and executable"
	@echo "  distclean    - Remove all build files and directories"
	@echo "  install-deps - Install dependencies on Ubuntu/Debian"
	@echo "  install-deps-rpm - Install dependencies on CentOS/RHEL/Fedora"
	@echo "  run          - Build and run the application"
	@echo "  debug        - Build with debug flags"
	@echo "  release      - Build with release optimization"
	@echo "  test-db      - Test MySQL database connection"
	@echo "  setup-db     - Setup database schema"
	@echo "  help         - Show this help message"

# Phony targets
.PHONY: all clean distclean install-deps install-deps-rpm run debug release test-db setup-db help directories

# Dependencies (auto-generated by the compiler)
-include $(OBJECTS:.o=.d)

# Generate dependency files
$(BUILD_DIR)/%.d: $(SRC_DIR)/%.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -MM -MT '$(BUILD_DIR)/$*.o' $< > $@
